name: Send new files

on:
  push:
    branches:
      - main

jobs:
  send_new_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find new files
        id: find_files
        run: |
          git fetch origin main
          base=$(git rev-parse FETCH_HEAD^1)
          head=$(git rev-parse FETCH_HEAD)
          changed_files=$(git diff --name-only $base $head | grep '^content/bot/')
          if [ -n "$changed_files" ]; then
          for file in $changed_files; do
          echo "Content of $file:"
          cat "$file"
          done
          else
          echo "No changed files found in 'content/bot/'."
          fi

      - name: Send files
        if: steps.find_files.outputs.files != ''
        run: |
          for file in ${{ steps.find_files.outputs.files }}; do
            curl -X POST -H "Content-Type: text/markdown" --data-binary "@$file" https://15d3-77-120-226-129.ngrok-free.app/create-bot
          done
