name: Send new files

on:
  push:
    branches:
      - main
    paths:
      - 'content/bot/**'

jobs:
  send_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Find Modified Files
        id: files
        uses: lots0logs/gh-action-get-changed-files@2.1.4
        with:
          format: 'space-delimited'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Changed Files
        run: |
          echo "Changed Files: ${{ steps.files.outputs.all }}"

      - name: Curl POST Changed Files
        run: |
          files_string=${{ steps.files.outputs.all }}
          files_string=$(echo $files_string | tr -d '[]' | tr ',' '\n')
          for file in $files_string; do
            echo "File path: $file"
            if [[ $file =~ ^content/bot/ ]]; then
              echo "Processing file: $file"
              curl -X POST -F "file=@${{ github.workspace }}/$file" https://15d3-77-120-226-129.ngrok-free.app/create-bot
            fi
          done